#!/bin/bash

case $1 in
clean)
    rm -f target/classes/*.class 
    rm -f target/App.jar
    ;;

build)
    javac -cp src -d target/classes src/App.java
    ;;

package)
    jar -cfe target/App.jar App target/classes/*.class
    ;;

run)
    java -cp target/classes/ App
    ;;
esac
